# Generated by Django 4.2.7 on 2023-11-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortner',
            name='long_url',
            field=models.URLField(max_length=30000),
        ),
    ]
